"""empty message

Revision ID: 250e7c4d55f1
Revises: f0100a9d5402
Create Date: 2018-11-30 12:46:43.348512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250e7c4d55f1'
down_revision = 'f0100a9d5402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', sa.String(length=24), nullable=True))
    op.create_index(op.f('ix_user_key'), 'user', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_key'), table_name='user')
    op.drop_column('user', 'key')
    # ### end Alembic commands ###
